// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, r.id FROM roles r WHERE r.name = $2
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.Name)
	return err
}

const consumeEmailVerification = `-- name: ConsumeEmailVerification :one
UPDATE email_verifications SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeEmailVerification(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerification, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const consumePasswordReset = `-- name: ConsumePasswordReset :one
UPDATE password_resets SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumePasswordReset, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE totp_recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
RETURNING id
`

type ConsumeRecoveryCodeParams struct {
	UserID   uuid.UUID
	CodeHash string
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createApiKey = `-- name: CreateApiKey :exec

INSERT INTO api_keys (id, user_id, key_hash, name, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateApiKeyParams struct {
	ID        string
	UserID    uuid.UUID
	KeyHash   string
	Name      string
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
}

// ── API keys (v0.9) ─────────────────────────────────────────
func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) error {
	_, err := q.db.Exec(ctx, createApiKey,
		arg.ID,
		arg.UserID,
		arg.KeyHash,
		arg.Name,
		arg.Scopes,
		arg.ExpiresAt,
	)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateEmailVerificationParams struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreatePasswordResetParams struct {
	TokenHash string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.Exec(ctx, createPasswordReset, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

type CreateRefreshTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreateRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description)
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateRoleParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, status, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM totp_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE name = $1
`

func (q *Queries) DeleteRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRole, name)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableTotp = `-- name: DisableTotp :exec
UPDATE users SET totp_secret = NULL, totp_enabled = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DisableTotp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableTotp, id)
	return err
}

const enableTotp = `-- name: EnableTotp :exec
UPDATE users SET totp_enabled = true, updated_at = now() WHERE id = $1
`

func (q *Queries) EnableTotp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableTotp, id)
	return err
}

const fetchUnpublishedOutbox = `-- name: FetchUnpublishedOutbox :many
SELECT id, aggregate_id, event_type, payload
FROM outbox
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
`

type FetchUnpublishedOutboxRow struct {
	ID          uuid.UUID
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) FetchUnpublishedOutbox(ctx context.Context, limit int32) ([]FetchUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, fetchUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchUnpublishedOutboxRow
	for rows.Next() {
		var i FetchUnpublishedOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, user_id, scopes, expires_at, revoked_at
FROM api_keys
WHERE key_hash = $1
`

type GetApiKeyByHashRow struct {
	ID        string
	UserID    uuid.UUID
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (GetApiKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i GetApiKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description
FROM roles
WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, status, email_verified, failed_login_attempts, locked_until, totp_secret, totp_enabled, deleted_at, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                  uuid.UUID
	Email               string
	PasswordHash        string
	Status              string
	EmailVerified       bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	TotpSecret          *string
	TotpEnabled         bool
	DeletedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, status, email_verified, failed_login_attempts, locked_until, totp_secret, totp_enabled, deleted_at, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                  uuid.UUID
	Email               string
	PasswordHash        string
	Status              string
	EmailVerified       bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	TotpSecret          *string
	TotpEnabled         bool
	DeletedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.name
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.name
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPermissionToRole = `-- name: GrantPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = $1 AND p.name = $2
ON CONFLICT DO NOTHING
`

type GrantPermissionToRoleParams struct {
	Name   string
	Name_2 string
}

func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, grantPermissionToRole, arg.Name, arg.Name_2)
	return err
}

const incrementLoginFailure = `-- name: IncrementLoginFailure :one
UPDATE users SET failed_login_attempts = failed_login_attempts + 1
WHERE id = $1
RETURNING failed_login_attempts
`

func (q *Queries) IncrementLoginFailure(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementLoginFailure, id)
	var failed_login_attempts int32
	err := row.Scan(&failed_login_attempts)
	return failed_login_attempts, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor_id, actor_email, action, target, detail)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditEventParams struct {
	ActorID    string
	ActorEmail string
	Action     string
	Target     string
	Detail     string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorID,
		arg.ActorEmail,
		arg.Action,
		arg.Target,
		arg.Detail,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec

INSERT INTO outbox (aggregate_id, event_type, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
}

// ── Transactional outbox ────────────────────────────────────
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO totp_recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	UserID   uuid.UUID
	CodeHash string
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS(SELECT 1 FROM revoked_tokens WHERE jti = $1)
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserActive = `-- name: IsUserActive :one
SELECT (deleted_at IS NULL)::boolean FROM users WHERE id = $1
`

func (q *Queries) IsUserActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserActive, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listApiKeysByUser = `-- name: ListApiKeysByUser :many
SELECT id, name, scopes, expires_at, last_used_at, created_at
FROM api_keys
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListApiKeysByUserRow struct {
	ID         string
	Name       string
	Scopes     []string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListApiKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListApiKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysByUserRow
	for rows.Next() {
		var i ListApiKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_id, actor_email, action, target, detail, created_at
FROM audit_events
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.Target,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, description
FROM permissions
ORDER BY name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionNames = `-- name: ListRolePermissionNames :many
SELECT p.name
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.name
`

func (q *Queries) ListRolePermissionNames(ctx context.Context, roleID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissionNames, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description
FROM roles
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
UPDATE users SET locked_until = $2, failed_login_attempts = 0 WHERE id = $1
`

type LockUserParams struct {
	ID          uuid.UUID
	LockedUntil pgtype.Timestamptz
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified = true WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const resetLoginState = `-- name: ResetLoginState :exec
UPDATE users SET failed_login_attempts = 0, locked_until = NULL WHERE id = $1
`

func (q *Queries) ResetLoginState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginState, id)
	return err
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users SET deleted_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const revokeAccessJTI = `-- name: RevokeAccessJTI :exec
INSERT INTO revoked_tokens (jti, expires_at)
VALUES ($1, $2)
ON CONFLICT (jti) DO NOTHING
`

type RevokeAccessJTIParams struct {
	Jti       string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RevokeAccessJTI(ctx context.Context, arg RevokeAccessJTIParams) error {
	_, err := q.db.Exec(ctx, revokeAccessJTI, arg.Jti, arg.ExpiresAt)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeApiKey = `-- name: RevokeApiKey :exec
UPDATE api_keys SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeApiKeyParams struct {
	ID     string
	UserID uuid.UUID
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) error {
	_, err := q.db.Exec(ctx, revokeApiKey, arg.ID, arg.UserID)
	return err
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permissions rp
WHERE rp.role_id = (SELECT r.id FROM roles r WHERE r.name = $1)
  AND rp.permission_id = (SELECT p.id FROM permissions p WHERE p.name = $2)
`

type RevokePermissionFromRoleParams struct {
	Name   string
	Name_2 string
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.Name, arg.Name_2)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeRoleFromUser = `-- name: RevokeRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1
  AND role_id = (SELECT id FROM roles WHERE name = $2)
`

type RevokeRoleFromUserParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, revokeRoleFromUser, arg.UserID, arg.Name)
	return err
}

const setTotpSecret = `-- name: SetTotpSecret :exec

UPDATE users SET totp_secret = $2, totp_enabled = false, updated_at = now() WHERE id = $1
`

type SetTotpSecretParams struct {
	ID         uuid.UUID
	TotpSecret *string
}

// ── 2FA / TOTP (v0.9) ───────────────────────────────────────
func (q *Queries) SetTotpSecret(ctx context.Context, arg SetTotpSecretParams) error {
	_, err := q.db.Exec(ctx, setTotpSecret, arg.ID, arg.TotpSecret)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const touchApiKey = `-- name: TouchApiKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchApiKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchApiKey, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET description = $2
WHERE name = $1
RETURNING id, name, description
`

type UpdateRoleParams struct {
	Name        string
	Description string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
