// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         int64
	ActorID    string
	ActorEmail string
	Action     string
	Target     string
	Detail     string
	CreatedAt  pgtype.Timestamptz
}

type EmailVerification struct {
	TokenHash  string
	UserID     uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PasswordReset struct {
	TokenHash  string
	UserID     uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Permission struct {
	ID          int64
	Name        string
	Description string
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RevokedToken struct {
	Jti       string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Role struct {
	ID          int64
	Name        string
	Description string
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type User struct {
	ID                  uuid.UUID
	Email               string
	PasswordHash        string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	EmailVerified       bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
}

type UserRole struct {
	UserID uuid.UUID
	RoleID int64
}
