// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (aggregate_id, event_type, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

const fetchUnpublishedOutbox = `-- name: FetchUnpublishedOutbox :many
SELECT id, aggregate_id, event_type, payload
FROM outbox
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
`

type FetchUnpublishedOutboxRow struct {
	ID          uuid.UUID
	AggregateID uuid.UUID
	EventType   string
	Payload     []byte
}

func (q *Queries) FetchUnpublishedOutbox(ctx context.Context, limit int32) ([]FetchUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, fetchUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchUnpublishedOutboxRow
	for rows.Next() {
		var i FetchUnpublishedOutboxRow
		if err := rows.Scan(&i.ID, &i.AggregateID, &i.EventType, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
